# Generated by Django 5.1.4 on 2024-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0002_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_phone_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="company_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_phone_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="company_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
