# Generated by Django 5.1.4 on 2025-02-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0004_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logged_in",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
