# Generated by Django 5.1.4 on 2025-02-14 14:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0005_user_is_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_image"
            ),
        ),
    ]
