# Generated by Django 4.2.4 on 2024-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "monthly_salary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("no_of_opening", models.IntegerField(blank=True, null=True)),
                (
                    "application_starting_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "application_ending_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
    ]
