# Generated by Django 4.2.4 on 2024-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_job_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="application_ending_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="application_starting_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
