# Generated by Django 5.1.4 on 2024-12-12 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_job_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationform",
            old_name="status",
            new_name="job_status",
        ),
    ]
