# Generated by Django 5.1.4 on 2024-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_job_api", "0002_rename_status_applicationform_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="job_status",
            field=models.TextField(blank=True, default="under_review", null=True),
        ),
    ]
