# Generated by Django 5.1.4 on 2024-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_job_api", "0003_alter_applicationform_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="application_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="application_ending_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="application_starting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
