# Generated by Django 5.1.4 on 2025-02-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_job_api", "0005_job_job_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="jobfiles"),
        ),
    ]
